
baseURL = "https://disegnando.com/"
title = "Disegnando"
paginate = 5
theme = "PaperMod"
languageCode = "it-it"
defaultContentLanguage = "it"
DateFormat = "02/01/2006"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true


[params]
env = "production"
title = "Disegnando"
description = "Blog di Paolo Zambetti"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = "Paolo Zambetti"
# author = ["Me", "You"]
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "02/01/2006"

defaultTheme = "light"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false


[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"


[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35


[params.profileMode]
enabled = false
title = "Disegnando"
subtitle = "Blog di Paolo Zambetti"
imageUrl = "/images/foto_tessera.png"
imageWidth = 332
imageHeight = 394
imageTitle = "my image"


[[params.profileMode.buttons]]
name = "Posts"
url = "posts"


[[params.profileMode.buttons]]
name = "Tags"
url = "tags"



[params.homeInfoParams]
Title = "La bellezza e la tecnica"
Content = """
Benvenuto. Qui puoi trovare approfondimenti sulla progettazione tecnica con una particolare attenzione all'estetica. 

Ti sarà capitato di sentir parlare della dicotomia tra arte e tecnica come di due mondi separati e vissuti da persone diverse con pratiche opposte: pittori da un lato e ingegneri dall'altro, poesia contro matematica. E' una visione particolarmente ingenua, soprattutto in Italia, dove ha vissuto l'artista ingegnere più famoso della storia: Leonardo Da Vinci!

A prima vista il disegno tecnico sembra una disciplina asettica e priva di emozioni, la cui funzione è veicolare informazioni principalmente geometriche. In realtà in ogni prodotto umano c'è almeno un briciolo di creatività e nel disegno tecnico ne serve molta. 

Quello che cambia è il modo in cui questa si esprime: l'artista elabora le sue idee in uno spazio libero vuoto immacolato, mentre il tecnico lo fa in uno spazio formalizzato pieno di vincoli fisici, economici, ecc. Per molti questo spazio è soffocante, ma i tecnici lo trovano stimolante. Un po' come un gioco che ha senso solo in virtù delle sue regole.

L'estetica è lo strumento perfetto per esplorare lo spazio delle soluzioni. La ricerca della bellezza ti costringe ad analizzare profondamente la funzione, a rivedere le forme o trovarne di nuove. Un progetto elegante porterà gli utenti ad essere positivamente coinvolti e partecipi. 
Esprimi il meglio di te e costruisci la tua reputazione.

Buon disegno.  
"""


[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/paolo-zambetti"


[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@Disegnando-z2u"


[[params.socialIcons]]
name = "github"
url = "https://github.com/ZambettiPaolo"



[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"



[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true



[params.editPost]
URL = "https://github.com/<path_to_repo>/content"
Text = "Suggest Changes"
appendFilePath = true



[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]



[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10


[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20


#[[menu.main]]
#identifier = "example"
#name = "example.org"
#url = "https://example.org"
#weight = 30



pygmentsUseClasses = true


[markup.highlight]
noClasses = false
